Ensure processor has extracted all members when members=None
fatiando/pooch pull request #365
Opened 2023-06-17 03:00 UTC by jni

Here's an early attempt at fixing #364. Currently, test_unpacking is failing
because of the log tests. I'm not 100% sure what to do about them because the
log becomes pretty complex, so I don't know how to generate the expected log.
Maybe this is the wrong approach — happy to revert the last commit and try
something else if you have suggestions! 🙏

## Commits

- Add failing test for #364
- Add _all_members method for when members=None

**Relevant issues/PRs:**

Fixes #364

2023-06-29 14:53 UTC, jni commented
👋

2023-10-20 16:21 UTC, leouieda commented
Hi @jni sorry for the very very long delay on this. We'll try to put out the fire on #373 and then get on this.

2023-10-20 16:41 UTC, leouieda commented
@jni I think the problem is that you're changing the value of `self.members`. There is a check in `_extract_file` for `self.members is None` to decide how to extract and that check is now always false. I think the fix would be to set a local `members` variable in `__call__` that either is `self._all_members(fname)` or `self.members`.

2023-10-30 08:39 UTC, jni commented
Thanks @leouieda! I'm sure I have older neglected PRs as a maintainer. 😂 And your suggestion seems to have done the trick! 🚀

2023-10-30 12:19 UTC, leouieda requested changes
@jni small comment on the test and I think Black and pylint are complaining 😬 

Thanks for this!

2023-10-30 12:19 UTC, leouieda commented on pooch/tests/test_processors.py
> +        assert len(filenames1) == 0
```suggestion
        processor1 = processor_class(members=["tiny-data.txt"])
        filenames1 = pup.fetch("store" + extension, processor=processor1)
        assert len(filenames1) == 1
```

@jni wouldn't it make more sense to test extracting a single file that does exist? This should still cause a problem with the old behavior right? Plus, using a bad file name should really cause an error (as you mentioned previously, probably best to open a separate issue 🙂).

2024-02-12 11:40 UTC, leouieda approved these changes

2024-02-12 11:49 UTC, leouieda commented
@jni sorry for the delay on this. I'll get these documentation issues fixed in main and then merge this asap. Thanks for your help!

2024-02-17 23:02 UTC, jni commented
@leouieda don't worry, I am very comfortable with long-lived PRs. 😂 I appreciate your efforts! 🙏 Please let me know if I can do anything else.

2024-02-19 14:47 UTC, merged

2024-02-19 14:49 UTC, leouieda commented
Alright! I made some slight modifications to make ExtratorProcessor an abstract base class. That got rid of the need to check if methods are implemented and made the tests and checks pass with our new pylint configuration.

Thanks for the contribution @jni! ❤️